'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eCommercePrioritizationCtrl

    '''<summary>
    '''rampeCommercePrioritizationCtrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rampeCommercePrioritizationCtrl As Global.Telerik.Web.UI.RadAjaxManagerProxy

    '''<summary>
    '''tbleCommercePrioritizationCtrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbleCommercePrioritizationCtrl As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblEMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbEMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbEMM As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblCMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCMG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbCMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbCMG As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblBuyer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbBuyer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbBuyer As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbLabel As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblTurnInWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTurnInWeek As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbTUWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbTUWeek As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblImageId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbImageId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbImageId As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorStyle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbVndSty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbVndSty As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbStatus As Global.Telerik.Web.UI.RadComboBox
End Class
