'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PrintPreTurnInSetUpCreate

    '''<summary>
    '''rsPrintPreTurnInSetUpCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsPrintPreTurnInSetUpCreate As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''rpHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpHeader As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rtbPrintPreTurnInSetUpCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbPrintPreTurnInSetUpCreate As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''pnlTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTabStrip As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rtsPrintPreTurnInSetUpCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtsPrintPreTurnInSetUpCreate As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''lblPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpPrintPreTurnInSetUpCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpPrintPreTurnInSetUpCreate As Global.TurnInProcessAutomation.MessagePanel

    '''<summary>
    '''rpContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpContent As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rmpPrintPreTurnInSetUpCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmpPrintPreTurnInSetUpCreate As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''pvAdLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvAdLevel As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''pnlAdLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdLevel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAdNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoDescLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoDescLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoDescText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoDescText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRunStartLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRunStartLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRunStartText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRunStartText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageNoDescLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNoDescLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageNoDescText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNoDescText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRunEndLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRunEndLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRunEndText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRunEndText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrintType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbPrintType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPrintType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''pvResultList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvResultList As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''pnlResultList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResultList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAdNoWorkListLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoWorkListLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoWorkListText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoWorkListText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoDescWorkListLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoDescWorkListLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoDescWorkListText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoDescWorkListText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRunStartWorkListLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRunStartWorkListLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRunStartWorkListText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRunStartWorkListText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageNoWorkListLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNoWorkListLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageNoWorkListText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNoWorkListText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageNoDescWorkListLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNoDescWorkListLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageNoDescWorkListText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNoDescWorkListText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRunEndWorkListLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRunEndWorkListLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRunEndWorkListText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRunEndWorkListText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdResultList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdResultList As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pvISNLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvISNLevel As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''pnlISNLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlISNLevel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblUserCreateDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserCreateDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUserCreateDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserCreateDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUserModifyDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserModifyDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUserModifyDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserModifyDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblISNLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISNLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbISNText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbISNText As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblVendorStyleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorStyleLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbVendorStyle As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblDeptLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeptText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBuyerExtLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyerExtLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBuyerExtText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyerExtText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVendorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVendorText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBrandLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrandLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBrandText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrandText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLabellbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabellbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLabel As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblFeatureImageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFeatureImageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFeatureImageText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFeatureImageText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblImageKindLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageKindLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbImageKind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbImageKind As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblFriendlyProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFriendlyProductDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFriendlyProductDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFriendlyProductDesc As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lblImageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbImageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbImageType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblSizeAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSizeAvailable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbSizeAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSizeAvailable As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblSizeCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSizeCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbSizeCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSizeCategory As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblNoOfModelsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoOfModelsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbNoOfModels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNoOfModels As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblFriendlyProductFeatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFriendlyProductFeatures As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFriendlyProductFeatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFriendlyProductFeatures As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lblModelAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModelAge As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbModelAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbModelAge As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblVendorApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorApproval As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbVendorApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbVendorApproval As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblModelCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModelCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbModelCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbModelCategory As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblColorCorrect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColorCorrect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbColorCorrect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbColorCorrect As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblMerchantNotesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMerchantNotesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMerchantNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMerchantNotes As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lblStoreSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStoreSample As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbStoreSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStoreSample As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblSampleStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSampleStore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbSampleStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSampleStore As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblAdditionalColorsSamples control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdditionalColorsSamples As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbAdditionalColorsSamples control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAdditionalColorsSamples As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblOfferTextNonPPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfferTextNonPPM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadTextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lblSellingLocationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSellingLocationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbSellingLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSellingLocation As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblTurnInUsageIndicatorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTurnInUsageIndicatorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbTurnInUsageIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTurnInUsageIndicator As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pvColorSizeLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvColorSizeLevel As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''pnlColorSizeLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlColorSizeLevel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoColorSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoColorSizeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoColorSizeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoColorSizeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoDescColorSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoDescColorSizeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoDescColorSizeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoDescColorSizeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoRunStartColorSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoRunStartColorSizeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoRunStartColorSizeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoRunStartColorSizeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoPageNoColorSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoPageNoColorSizeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbPageNoColorSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPageNoColorSize As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblAdNoPageNoDescColorSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoPageNoDescColorSizeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoPageNoDescColorSizeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoPageNoDescColorSizeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoRunEndColorSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoRunEndColorSizeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoRunEndColorSizeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoRunEndColorSizeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeptColorSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptColorSizeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeptColorSizeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptColorSizeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBuyerColorSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyerColorSizeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBuyerColorSizeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyerColorSizeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBuyerExtColorSizeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyerExtColorSizeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBuyerExtColorSizeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyerExtColorSizeText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdColorSizeLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdColorSizeLevel As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''hdnVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVendorStyle As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As TurnInProcessAutomation.ContentPage
        Get
            Return CType(MyBase.Master, TurnInProcessAutomation.ContentPage)
        End Get
    End Property
End Class
