'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TurnInQueryCtrl

    '''<summary>
    '''rampTurnInQueryCtrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rampTurnInQueryCtrl As Global.Telerik.Web.UI.RadAjaxManagerProxy

    '''<summary>
    '''tblTurnInQueryCtrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblTurnInQueryCtrl As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblView As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblViewType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblViewType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblCRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCRG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbCRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCRG As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblCMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCMG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbCMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCMG As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ToolTipValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolTipValidator1 As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''lblCFG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbCFG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCFG As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ToolTipValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolTipValidator2 As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''lblBuyer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbBuyer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBuyer As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ToolTipValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolTipValidator3 As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''lblFOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbFOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFOB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDept As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDept As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbClass As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblACode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbACode As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblVendor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendor1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbVendor As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorStyle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbVendorStyle As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblTurnInStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTurnInStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbTurnInStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTurnInStatus As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rbShowDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbShowDialog As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''modalPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalPopup As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''lblTurnInType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTurnInType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbTurnInType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTurnInType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dpTurninFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpTurninFrom As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''ImgTurnInFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgTurnInFrom As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dpTurninTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpTurninTo As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''ImgTurnInTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgTurnInTo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBatch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBatchNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ttvBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttvBatch As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''tblSQFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSQFields As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblAdNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbAdNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAdNo As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ttvAds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttvAds As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbRouteFromAd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbRouteFromAd As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tblPMfields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPMfields As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblAdNoPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoPM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbAdNoPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAdNoPM As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ToolTipValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolTipValidator4 As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''lblPageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbPageNumber As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblInWebCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInWebCat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbInWebCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbInWebCat As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuffix As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSuffix As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblImageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbImageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbImageType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblModelCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModelCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbModelCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbModelCategory As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblFeatWebCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFeatWebCat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbFeatWebCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFeatWebCat As Global.Telerik.Web.UI.RadComboBox
End Class
