'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSErrorReporting
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx", ConfigurationName:="WSErrorReporting.WSErrorReportingSoap")>  _
    Public Interface WSErrorReportingSoap
        
        'CODEGEN: Generating message contract since element name Path from namespace http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx/database"& _ 
            "_error", ReplyAction:="*")>  _
        Function database_error(ByVal request As WSErrorReporting.database_errorRequest) As WSErrorReporting.database_errorResponse
        
        'CODEGEN: Generating message contract since element name Path from namespace http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx/applicat"& _ 
            "ion_error", ReplyAction:="*")>  _
        Function application_error(ByVal request As WSErrorReporting.application_errorRequest) As WSErrorReporting.application_errorResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class database_errorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="database_error", [Namespace]:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx", Order:=0)>  _
        Public Body As WSErrorReporting.database_errorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSErrorReporting.database_errorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx")>  _
    Partial Public Class database_errorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Path As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public RawURL As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public openSystemApplication As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public LastSQLString As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public LastSQLParms As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public MachineName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public UserIP As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public LogonUser As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public FullExc As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public OwnershipID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Path As String, ByVal RawURL As String, ByVal openSystemApplication As String, ByVal LastSQLString As String, ByVal LastSQLParms As String, ByVal MachineName As String, ByVal UserIP As String, ByVal LogonUser As String, ByVal FullExc As String, ByVal OwnershipID As String)
            MyBase.New
            Me.Path = Path
            Me.RawURL = RawURL
            Me.openSystemApplication = openSystemApplication
            Me.LastSQLString = LastSQLString
            Me.LastSQLParms = LastSQLParms
            Me.MachineName = MachineName
            Me.UserIP = UserIP
            Me.LogonUser = LogonUser
            Me.FullExc = FullExc
            Me.OwnershipID = OwnershipID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class database_errorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="database_errorResponse", [Namespace]:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx", Order:=0)>  _
        Public Body As WSErrorReporting.database_errorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSErrorReporting.database_errorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx")>  _
    Partial Public Class database_errorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public database_errorResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal database_errorResult As String)
            MyBase.New
            Me.database_errorResult = database_errorResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class application_errorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="application_error", [Namespace]:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx", Order:=0)>  _
        Public Body As WSErrorReporting.application_errorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSErrorReporting.application_errorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx")>  _
    Partial Public Class application_errorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Path As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public RawURL As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public openSystemApplication As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public StackTrace As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public MachineName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public UserIP As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public LogonUser As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public FullExc As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public OwnershipID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Path As String, ByVal RawURL As String, ByVal openSystemApplication As String, ByVal StackTrace As String, ByVal MachineName As String, ByVal UserIP As String, ByVal LogonUser As String, ByVal FullExc As String, ByVal OwnershipID As String)
            MyBase.New
            Me.Path = Path
            Me.RawURL = RawURL
            Me.openSystemApplication = openSystemApplication
            Me.StackTrace = StackTrace
            Me.MachineName = MachineName
            Me.UserIP = UserIP
            Me.LogonUser = LogonUser
            Me.FullExc = FullExc
            Me.OwnershipID = OwnershipID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class application_errorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="application_errorResponse", [Namespace]:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx", Order:=0)>  _
        Public Body As WSErrorReporting.application_errorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSErrorReporting.application_errorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://iChoose.test.bonton.com/WebServices/WSErrorReporting\Service.asmx")>  _
    Partial Public Class application_errorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public application_errorResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal application_errorResult As String)
            MyBase.New
            Me.application_errorResult = application_errorResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSErrorReportingSoapChannel
        Inherits WSErrorReporting.WSErrorReportingSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSErrorReportingSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSErrorReporting.WSErrorReportingSoap)
        Implements WSErrorReporting.WSErrorReportingSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSErrorReporting_WSErrorReportingSoap_database_error(ByVal request As WSErrorReporting.database_errorRequest) As WSErrorReporting.database_errorResponse Implements WSErrorReporting.WSErrorReportingSoap.database_error
            Return MyBase.Channel.database_error(request)
        End Function
        
        Public Function database_error(ByVal Path As String, ByVal RawURL As String, ByVal openSystemApplication As String, ByVal LastSQLString As String, ByVal LastSQLParms As String, ByVal MachineName As String, ByVal UserIP As String, ByVal LogonUser As String, ByVal FullExc As String, ByVal OwnershipID As String) As String
            Dim inValue As WSErrorReporting.database_errorRequest = New WSErrorReporting.database_errorRequest()
            inValue.Body = New WSErrorReporting.database_errorRequestBody()
            inValue.Body.Path = Path
            inValue.Body.RawURL = RawURL
            inValue.Body.openSystemApplication = openSystemApplication
            inValue.Body.LastSQLString = LastSQLString
            inValue.Body.LastSQLParms = LastSQLParms
            inValue.Body.MachineName = MachineName
            inValue.Body.UserIP = UserIP
            inValue.Body.LogonUser = LogonUser
            inValue.Body.FullExc = FullExc
            inValue.Body.OwnershipID = OwnershipID
            Dim retVal As WSErrorReporting.database_errorResponse = CType(Me,WSErrorReporting.WSErrorReportingSoap).database_error(inValue)
            Return retVal.Body.database_errorResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSErrorReporting_WSErrorReportingSoap_application_error(ByVal request As WSErrorReporting.application_errorRequest) As WSErrorReporting.application_errorResponse Implements WSErrorReporting.WSErrorReportingSoap.application_error
            Return MyBase.Channel.application_error(request)
        End Function
        
        Public Function application_error(ByVal Path As String, ByVal RawURL As String, ByVal openSystemApplication As String, ByVal StackTrace As String, ByVal MachineName As String, ByVal UserIP As String, ByVal LogonUser As String, ByVal FullExc As String, ByVal OwnershipID As String) As String
            Dim inValue As WSErrorReporting.application_errorRequest = New WSErrorReporting.application_errorRequest()
            inValue.Body = New WSErrorReporting.application_errorRequestBody()
            inValue.Body.Path = Path
            inValue.Body.RawURL = RawURL
            inValue.Body.openSystemApplication = openSystemApplication
            inValue.Body.StackTrace = StackTrace
            inValue.Body.MachineName = MachineName
            inValue.Body.UserIP = UserIP
            inValue.Body.LogonUser = LogonUser
            inValue.Body.FullExc = FullExc
            inValue.Body.OwnershipID = OwnershipID
            Dim retVal As WSErrorReporting.application_errorResponse = CType(Me,WSErrorReporting.WSErrorReportingSoap).application_error(inValue)
            Return retVal.Body.application_errorResult
        End Function
    End Class
End Namespace
