'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CopyPrioritizationSearchCtrl

    '''<summary>
    '''RadAjaxManagerProxy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerProxy1 As Global.Telerik.Web.UI.RadAjaxManagerProxy

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''rcb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcb As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''splM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents splM As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''pNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNav As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''slZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slZone As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''slPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slPane As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''phCopyFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phCopyFilter As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblPriceStatusHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceStatusHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cblPriceStatusCodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblPriceStatusCodes As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''lblCopyHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCopyHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkCopyReady control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCopyReady As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCopyNotReady control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCopyNotReady As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblFinalImageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalImageHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkImageAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImageAvailable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkImageNotAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImageNotAvailable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSKUUseHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSKUUseHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkBasic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBasic As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkFashion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFashion As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPWP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkGWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGWP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSpecial As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCollateral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCollateral As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVirtualGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVirtualGC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPlasticGC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPlasticGC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMiscHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMiscHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkOnHand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOnHand As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOnOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOnOrder As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkINFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkINFC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDropship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDropship As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pMainNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pMainNav As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rpbResultsTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpbResultsTab As Global.Telerik.Web.UI.RadPanelBar

    '''<summary>
    '''hdnVendorStyles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVendorStyles As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''rcb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcb1 As Global.Telerik.Web.UI.RadCodeBlock
End Class
