'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GXSCatalogueExtendedPropertiesCtrl

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SSHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SSHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divVendorStyle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spVendorStyle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVendorStyle As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divFullProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFullProductName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spFullProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spFullProductName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFullProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFullProductName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divUPC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUPC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spUPC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spUPC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtUPC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUPC As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divNRFColorCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNRFColorCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spNRFColorCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spNRFColorCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNRFColorCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNRFColorCode As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divColorDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divColorDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spColorDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spColorDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtColorDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColorDescription As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divNRFSizeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNRFSizeCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spNRFSizeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spNRFSizeCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNRFSizeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNRFSizeCode As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divSizeDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSizeDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spSizeDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spSizeDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSizeDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSizeDescription As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divBrandName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBrandName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spBrandName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spBrandName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtBrandName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBrandName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divVendorCollectionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divVendorCollectionName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spVendorCollectionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spVendorCollectionName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtVendorCollectionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVendorCollectionName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divTeamName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTeamName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spTeamName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spTeamName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtTeamName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeamName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerQtyOfUnitsInPkg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerQtyOfUnitsInPkg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerQtyOfUnitsInPkg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerQtyOfUnitsInPkg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerQtyOfUnitsInPkg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerQtyOfUnitsInPkg As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divCountryOfOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCountryOfOrigin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spCountryOfOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spCountryOfOrigin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCountryOfOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountryOfOrigin As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divMarketingMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMarketingMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spMarketingMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spMarketingMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtMarketingMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMarketingMessage As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divFabricOrMaterialDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFabricOrMaterialDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spFabricOrMaterialDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spFabricOrMaterialDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFabricOrMaterialDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFabricOrMaterialDescription As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divLiningMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLiningMaterial As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spLiningMaterials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spLiningMaterials As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtLiningMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLiningMaterial As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''Div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divGoldCarat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGoldCarat As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spGoldCarat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spGoldCarat As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtGoldCarat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoldCarat As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divStoneDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStoneDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spStoneDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spStoneDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtStoneDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStoneDetails As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divClosure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divClosure As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spClosure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spClosure As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtClosure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClosure As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divCareInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCareInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spCareInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spCareInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCareInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCareInfo As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerItemLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerItemLength As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerItemLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerItemLength As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerItemLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerItemLength As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerItemWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerItemWidth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerItemWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerItemWidth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerItemWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerItemWidth As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerItemDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerItemDepth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerItemDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerItemDepth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerItemDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerItemDepth As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerItemHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerItemHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerItemHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerItemHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerItemHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerItemHeight As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divHeelHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHeelHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spHeelHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spHeelHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtHeelHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHeelHeight As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divPlatformHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPlatformHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spPlatformHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spPlatformHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtPlatformHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlatformHeight As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divSoleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSoleType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spSoleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spSoleType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSoleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoleType As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divBootLegCircumference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBootLegCircumference As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spBootLegCircumference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spBootLegCircumference As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtBootLegCircumference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBootLegCircumference As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divBootShaftHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBootShaftHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spBootShaftHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spBootShaftHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtBootShaftHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBootShaftHeight As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divEarringsDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEarringsDrop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spEarringsDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spEarringsDrop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtEarringsDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEarringsDrop As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divWatchBandWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWatchBandWidth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spWatchBandWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spWatchBandWidth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtWatchBandWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWatchBandWidth As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divWatchCaseSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWatchCaseSize As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spWatchCaseSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spWatchCaseSize As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtWatchCaseSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWatchCaseSize As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divHandbagShoulderDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHandbagShoulderDrop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spHandbagShoulderDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spHandbagShoulderDrop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtHandbagShoulderDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHandbagShoulderDrop As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerPackageDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerPackageDepth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerPackageDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerPackageDepth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerPackageDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerPackageDepth As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerPackageHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerPackageHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerPackageHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerPackageHeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerPackageHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerPackageHeight As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerPackageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerPackageWidth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerPackageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerPackageWidth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerPackageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerPackageWidth As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerPackageGrossWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerPackageGrossWeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerPackageGrossWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerPackageGrossWeight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerPackageGrossWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerPackageGrossWeight As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divClosure2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divClosure2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spClosure2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spClosure2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtClosure2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClosure2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divCollarType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCollarType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spCollarType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spCollarType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCollarType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCollarType As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divPantInseamLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPantInseamLength As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spPantInseamLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spPantInseamLength As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtPantInseamLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPantInseamLength As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divSleeveMeasurement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSleeveMeasurement As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spSleeveMeasurement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spSleeveMeasurement As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSleeveMeasurement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSleeveMeasurement As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divSleeveType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSleeveType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spSleeveType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spSleeveType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSleeveType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSleeveType As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divCareInfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCareInfo2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spCareInfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spCareInfo2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCareInfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCareInfo2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divWarrantyDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divWarrantyDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spWarrantyDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spWarrantyDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtWarrantyDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarrantyDescription As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divConsumerProductCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsumerProductCapacity As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spConsumerProductCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spConsumerProductCapacity As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtConsumerProductCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerProductCapacity As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divKeyActiveIngredient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divKeyActiveIngredient As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spKeyActiveIngredient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spKeyActiveIngredient As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtKeyActiveIngredient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKeyActiveIngredient As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divDoesNotContain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDoesNotContain As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spDoesNotContain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spDoesNotContain As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtDoesNotContain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDoesNotContain As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divAerosolProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAerosolProduct As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spAerosolProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spAerosolProduct As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtAerosolProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAerosolProduct As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divClosure3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divClosure3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spClosure3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spClosure3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtClosure3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClosure3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divFauxFur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFauxFur As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spFauxFur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spFauxFur As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFauxFur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFauxFur As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divFurAnimalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFurAnimalName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spFurAnimalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spFurAnimalName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFurAnimalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFurAnimalName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divFurCountryOfOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFurCountryOfOrigin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spFurCountryOfOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spFurCountryOfOrigin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFurCountryOfOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFurCountryOfOrigin As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divFurTreatment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFurTreatment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spFurTreatment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spFurTreatment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFurTreatment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFurTreatment As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCodeBlock2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock2 As Global.Telerik.Web.UI.RadCodeBlock
End Class
