'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GXSCatalogueStyleSKUPropertiesCtrl

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SSHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SSHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divFabrication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFabrication As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFabrication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFabrication As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divSellingLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSellingLoc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSellingLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSellingLoc As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divProdDtl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProdDtl1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtProdDtl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdDtl1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divProdDtl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProdDtl2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtProdDtl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdDtl2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divProdDtl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProdDtl3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtProdDtl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdDtl3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divAssembledIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAssembledIn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtAssembledIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssembledIn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divGenClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGenClass As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtGenClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGenClass As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divGenSubClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGenSubClass As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtGenSubClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGenSubClass As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBrand As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBrand As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabel As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divFabDtl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFabDtl As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFabDtl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFabDtl As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divLifestyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLifestyle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtLifestyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLifestyle As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divSeason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSeason As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSeason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSeason As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divOccasion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOccasion As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtOccasion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOccasion As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''divTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTheme As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTheme As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RadCodeBlock2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock2 As Global.Telerik.Web.UI.RadCodeBlock
End Class
