'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CopyPrioritization

    '''<summary>
    '''ralpCopyPriLoadPnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralpCopyPriLoadPnl As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''rapCopyPrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rapCopyPrioritization As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''rtbCopyPrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbCopyPrioritization As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''lblPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MessagePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessagePanel1 As Global.TurnInProcessAutomation.MessagePanel

    '''<summary>
    '''lblUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdateStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rtsCopyPrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtsCopyPrioritization As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''rmpCopyPrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmpCopyPrioritization As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''pvCopyPrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvCopyPrioritization As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''grdCopyPrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCopyPrioritization As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pvEditCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvEditCopy As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''lblProductNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductNotes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rigProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rigProduct As Global.Telerik.Web.UI.RadImageGallery

    '''<summary>
    '''lblAvailableSizes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvailableSizes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAvailableColors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvailableColors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblImageNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageNotes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rlbCopyPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlbCopyPreview As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''txtCopyPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCopyPreview As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''hdnCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCopy As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''rlbCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlbCopy As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''rlbGxs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlbGxs As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''rlbSsku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlbSsku As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''btnExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As TurnInProcessAutomation.ContentPage
        Get
            Return CType(MyBase.Master, TurnInProcessAutomation.ContentPage)
        End Get
    End Property
End Class
