'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eCommercePrioritization

    '''<summary>
    '''RadAjaxMgrProxyEcommPrior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxMgrProxyEcommPrior As Global.Telerik.Web.UI.RadAjaxManagerProxy

    '''<summary>
    '''rseCommercePrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rseCommercePrioritization As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''rpHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpHeader As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rtbeCommercePrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbeCommercePrioritization As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''lblPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpeCommercePrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeCommercePrioritization As Global.TurnInProcessAutomation.MessagePanel

    '''<summary>
    '''rpContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpContent As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''pnleCommercePrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnleCommercePrioritization As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hdnUpdateButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnUpdateButton As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnSpellCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSpellCheck As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tblFloodOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFloodOptions As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnFlood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFlood As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rcbFloodSwatchFlg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodSwatchFlg As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodColorFlg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodColorFlg As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodSizeFlg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodSizeFlg As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''hfFloodWebCatCde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFloodWebCatCde As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''rtxtFloodWebCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodWebCategories As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnOpenWebCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOpenWebCat As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rcbFloodLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodLabel As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodBrand As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodAge As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodGender As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tblFloodColorOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFloodColorOptions As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnFloodClrLvl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFloodClrLvl As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rtxtFloodFeatureId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodFeatureId As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rtxtFloodProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodProductName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtxtFloodImageGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodImageGroup As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''tblFloodSizeOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFloodSizeOptions As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnFloodSizLvl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFloodSizLvl As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rtxtFloodFindWebCatSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodFindWebCatSize As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtxtFloodReplaceWebCatSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodReplaceWebCatSize As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtxtFloodFindSizeFam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodFindSizeFam As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtxtFloodReplaceSizeFam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodReplaceSizeFam As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtxtFloodFindVendorSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodFindVendorSize As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtxtFloodVendorWCSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodVendorWCSize As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rcbFloodVendorWCSizeFamily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodVendorWCSizeFamily As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''divFScr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFScr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdeCommercePrioritization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdeCommercePrioritization As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadWinMgrPrior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWinMgrPrior As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''UserDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserDialog As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''FloodWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloodWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''tuModalExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuModalExport As Global.TurnInProcessAutomation.ModalPopupControl

    '''<summary>
    '''tuSnapshotImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuSnapshotImage As Global.TurnInProcessAutomation.ModalSnapshotImage

    '''<summary>
    '''RadCodeBlockEcommPrior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlockEcommPrior As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As TurnInProcessAutomation.ContentPage
        Get
            Return CType(MyBase.Master, TurnInProcessAutomation.ContentPage)
        End Get
    End Property
End Class
