'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class eCommTurnInMeet

    '''<summary>
    '''rseCommTurnInMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rseCommTurnInMaint As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''rpHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpHeader As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''tuModalOrderColors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuModalOrderColors As Global.TurnInProcessAutomation.ModalOrderColors

    '''<summary>
    '''rtbeCommTurnInMeet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbeCommTurnInMeet As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''lblPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpeCommTurnInMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeCommTurnInMaint As Global.TurnInProcessAutomation.MessagePanel

    '''<summary>
    '''RadPane1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane1 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''pnlTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTabStrip As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rtsTurnInMeet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtsTurnInMeet As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''rmpTurnInMeet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmpTurnInMeet As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''pveMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pveMM As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''tblFloodEMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFloodEMM As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnResetFloodEMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetFloodEMM As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnFloodEMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFloodEMM As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''hfFloodWebCatCde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFloodWebCatCde As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''rtxtFloodWebCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodWebCategories As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnOpenWebCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOpenWebCat As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rtxtFloodFrndPrdDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodFrndPrdDesc As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''valFloodFrndPrdDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFloodFrndPrdDesc As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''rtxtFloodFriendlyColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodFriendlyColor As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''valFriendlyColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFriendlyColor As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''rcbFloodSizeCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodSizeCategory As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rtxtFloodEMMNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodEMMNotes As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''valFloodEMMNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFloodEMMNotes As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''grdEMM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdEMM As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pvCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvCC As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''tblFloodCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFloodCC As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnResetFloodCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetFloodCC As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnFloodCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFloodCC As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rtxtFloodImageNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodImageNotes As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ToolTipValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolTipValidator1 As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''rtxtFloodStylingNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodStylingNotes As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ToolTipValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolTipValidator2 As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''cmbFloodFeatureRenderSwatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFloodFeatureRenderSwatch As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodImgType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodImgType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodModelCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodModelCategory As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodAlternateView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodAlternateView As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''grdCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCC As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pvCopyWriter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvCopyWriter As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''grdCopyWriter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCopyWriter As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''piModalExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents piModalExport As Global.TurnInProcessAutomation.ModalPopupControl

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''UserDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserDialog As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''FloodWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FloodWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''PreviewWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviewWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''btnImageFlipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImageFlipper As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SamplePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SamplePicker As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As TurnInProcessAutomation.ContentPage
        Get
            Return CType(MyBase.Master, TurnInProcessAutomation.ContentPage)
        End Get
    End Property
End Class
