'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PreTurnInSetUpCreate

    '''<summary>
    '''RadAjaxMgrProxyPreTurnInSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxMgrProxyPreTurnInSetup As Global.Telerik.Web.UI.RadAjaxManagerProxy

    '''<summary>
    '''rsPreTurnInCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsPreTurnInCreate As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''rpHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpHeader As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''tuModalOrderISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuModalOrderISN As Global.TurnInProcessAutomation.ModalOrderISN

    '''<summary>
    '''rtbPreTurnInCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbPreTurnInCreate As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''pnlTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTabStrip As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rtsAPAdjustment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtsAPAdjustment As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''lblPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MessagePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessagePanel1 As Global.TurnInProcessAutomation.MessagePanel

    '''<summary>
    '''mpPreTurnInCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpPreTurnInCreate As Global.TurnInProcessAutomation.MessagePanel

    '''<summary>
    '''rpContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpContent As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''pnlAdLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdLevel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblBatchId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBatchId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBatchIdText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBatchIdText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdNoDescText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNoDescText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnAdStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAdStartDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAdEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAdEndDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblPageNbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNbr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageNumberText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNumberText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnSysPgNbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSysPgNbr As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnBuyer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBuyer As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnISNTabChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnISNTabChanges As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnISNTabSaveFlg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnISNTabSaveFlg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblTurnInDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTurnInDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTurnInDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTurnInDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rmpPreTurnInCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmpPreTurnInCreate As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''pvAdList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvAdList As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''grdMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdMaint As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pvAdLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvAdLevel As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''pvResultList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvResultList As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdResultList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdResultList As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pvKilled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvKilled As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''pnlKilled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlKilled As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdKilled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdKilled As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pvISNLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvISNLevel As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''pnlISNLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlISNLevel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblISNLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISNLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbISNLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbISNLabel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblISNLongDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISNLongDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblISNLongDescText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISNLongDescText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUserModifyDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserModifyDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUserModifyDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserModifyDateText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVendorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVendorText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGenericClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenericClass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGenericClassTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenericClassTxt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductDetail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductDetail1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductDetail1Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductDetail1Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVendorStyleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorStyleLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVendorStyleLabelText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorStyleLabelText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGenericSubclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenericSubclass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGenericSubclassText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenericSubclassText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductDetail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductDetail2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductDetail2Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductDetail2Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBrandLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrandLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBrandText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrandText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPattern control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPattern As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPatternText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPatternText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductDetail3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductDetail3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductDetail3Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductDetail3Text As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLabellbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabellbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLabel As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ttvISNTabLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttvISNTabLabel As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''lblFeatureImageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFeatureImageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litFeatureImageText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litFeatureImageText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblWebCategoriesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebCategoriesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebCatText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebCatText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbWebCategoriesLevel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel1 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel1 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbWebCategoriesLevel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel2 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel2 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbWebCategoriesLevel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel3 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel3 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbWebCategoriesLevel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel4 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel4 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbWebCategoriesLevel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel5 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel5 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbWebCategoriesLevel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel6 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel6 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ddlCopyWebCatsFromISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCopyWebCatsFromISN As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCopyWebCatsFromISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopyWebCatsFromISN As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadAjaxLoadingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''grdWebCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdWebCategories As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lblDeptLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeptText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBuyerExtLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyerExtLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBuyerExtText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBuyerExtText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExistingWebStyleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExistingWebStyleLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExistingWebStyleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExistingWebStyleText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSellingLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSellingLoc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSellingLocText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSellingLocText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFabrication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFabrication As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFabricationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFabricationText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMadeIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMadeIn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMadeInText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMadeInText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDropShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDropShip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDropShipText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDropShipText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSizeCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSizeCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbSizeCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSizeCategory As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblVendorApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorApproval As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblVendorApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVendorApproval As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblModelCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModelCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbModelCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbModelCategory As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblAdditionalColorsSamples control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdditionalColorsSamples As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblAdditionalColorsSamples control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAdditionalColorsSamples As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblTurnInUsageIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTurnInUsageIndicator As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbTurnInUsageIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTurnInUsageIndicator As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''lblPageNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pvColorSizeLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvColorSizeLevel As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''pnlColorSizeLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlColorSizeLevel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tblFloodOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFloodOptions As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnResetFlood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetFlood As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnFlood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFlood As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rtxtFloodFrndPrdDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodFrndPrdDesc As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''valFloodFrndPrdDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFloodFrndPrdDesc As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''rtxtFloodFrndPrdFeat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodFrndPrdFeat As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''valFloodFrndPrdFeat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFloodFrndPrdFeat As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''rtxtFloodFriendlyColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodFriendlyColor As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''valFriendlyColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFriendlyColor As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''rcbFloodColorFamily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodColorFamily As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodClrCorrect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodClrCorrect As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodImgKind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodImgKind As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rtxtFloodGroupNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodGroupNum As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rcbFloodImgType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodImgType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodAltView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodAltView As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rcbFloodSampleStr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbFloodSampleStr As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rtxtFloodMerchNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtFloodMerchNotes As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''valFloodMerchNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFloodMerchNotes As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''grdColorSizeLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdColorSizeLevel As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''SamplePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SamplePicker As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''PreviewWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviewWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''btnImageFlipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImageFlipper As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As TurnInProcessAutomation.ContentPage
        Get
            Return CType(MyBase.Master, TurnInProcessAutomation.ContentPage)
        End Get
    End Property
End Class
