'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebCategories

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''rsmJS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsmJS As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''lblPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MessagePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessagePanel1 As Global.TurnInProcessAutomation.MessagePanel

    '''<summary>
    '''rsPreTurnInCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsPreTurnInCreate As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''rpHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpHeader As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rtbeCommWebCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbeCommWebCat As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''rpContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpContent As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''lblWebCategoriesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebCategoriesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbWebCategoriesLevel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel1 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel1 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ttvWebCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttvWebCat As Global.TurnInProcessAutomation.ToolTipValidator

    '''<summary>
    '''cmbWebCategoriesLevel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel2 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel2 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbWebCategoriesLevel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel3 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel3 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbWebCategoriesLevel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel4 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel4 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbWebCategoriesLevel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel5 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel5 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''cmbWebCategoriesLevel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWebCategoriesLevel6 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddWebCategoriesLevel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddWebCategoriesLevel6 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''grdWebCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdWebCategories As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
End Class
