'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace AdUpdates
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Ad", [Namespace]:="http://schemas.datacontract.org/2004/07/AdUpdates"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Ad
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdEndField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdStartField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdVersionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssocFirstField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssocIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssocLastField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssocPhoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EventEndField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EventNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EventStartField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MediaDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MediaTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageField As AdUpdates.Page
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhotoEndField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhotoStartField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TurninDateField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdDescription() As String
            Get
                Return Me.AdDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdDescriptionField, value) <> true) Then
                    Me.AdDescriptionField = value
                    Me.RaisePropertyChanged("AdDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdEnd() As Date
            Get
                Return Me.AdEndField
            End Get
            Set
                If (Me.AdEndField.Equals(value) <> true) Then
                    Me.AdEndField = value
                    Me.RaisePropertyChanged("AdEnd")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdNumber() As Integer
            Get
                Return Me.AdNumberField
            End Get
            Set
                If (Me.AdNumberField.Equals(value) <> true) Then
                    Me.AdNumberField = value
                    Me.RaisePropertyChanged("AdNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdStart() As Date
            Get
                Return Me.AdStartField
            End Get
            Set
                If (Me.AdStartField.Equals(value) <> true) Then
                    Me.AdStartField = value
                    Me.RaisePropertyChanged("AdStart")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdStatus() As String
            Get
                Return Me.AdStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdStatusField, value) <> true) Then
                    Me.AdStatusField = value
                    Me.RaisePropertyChanged("AdStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdVersion() As String
            Get
                Return Me.AdVersionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdVersionField, value) <> true) Then
                    Me.AdVersionField = value
                    Me.RaisePropertyChanged("AdVersion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssocFirst() As String
            Get
                Return Me.AssocFirstField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssocFirstField, value) <> true) Then
                    Me.AssocFirstField = value
                    Me.RaisePropertyChanged("AssocFirst")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssocId() As Integer
            Get
                Return Me.AssocIdField
            End Get
            Set
                If (Me.AssocIdField.Equals(value) <> true) Then
                    Me.AssocIdField = value
                    Me.RaisePropertyChanged("AssocId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssocLast() As String
            Get
                Return Me.AssocLastField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssocLastField, value) <> true) Then
                    Me.AssocLastField = value
                    Me.RaisePropertyChanged("AssocLast")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssocPhone() As String
            Get
                Return Me.AssocPhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssocPhoneField, value) <> true) Then
                    Me.AssocPhoneField = value
                    Me.RaisePropertyChanged("AssocPhone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EventEnd() As Date
            Get
                Return Me.EventEndField
            End Get
            Set
                If (Me.EventEndField.Equals(value) <> true) Then
                    Me.EventEndField = value
                    Me.RaisePropertyChanged("EventEnd")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EventName() As String
            Get
                Return Me.EventNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EventNameField, value) <> true) Then
                    Me.EventNameField = value
                    Me.RaisePropertyChanged("EventName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EventStart() As Date
            Get
                Return Me.EventStartField
            End Get
            Set
                If (Me.EventStartField.Equals(value) <> true) Then
                    Me.EventStartField = value
                    Me.RaisePropertyChanged("EventStart")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MediaDescription() As String
            Get
                Return Me.MediaDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MediaDescriptionField, value) <> true) Then
                    Me.MediaDescriptionField = value
                    Me.RaisePropertyChanged("MediaDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MediaType() As String
            Get
                Return Me.MediaTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MediaTypeField, value) <> true) Then
                    Me.MediaTypeField = value
                    Me.RaisePropertyChanged("MediaType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Page() As AdUpdates.Page
            Get
                Return Me.PageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PageField, value) <> true) Then
                    Me.PageField = value
                    Me.RaisePropertyChanged("Page")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PhotoEnd() As Date
            Get
                Return Me.PhotoEndField
            End Get
            Set
                If (Me.PhotoEndField.Equals(value) <> true) Then
                    Me.PhotoEndField = value
                    Me.RaisePropertyChanged("PhotoEnd")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PhotoStart() As Date
            Get
                Return Me.PhotoStartField
            End Get
            Set
                If (Me.PhotoStartField.Equals(value) <> true) Then
                    Me.PhotoStartField = value
                    Me.RaisePropertyChanged("PhotoStart")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TurninDate() As Date
            Get
                Return Me.TurninDateField
            End Get
            Set
                If (Me.TurninDateField.Equals(value) <> true) Then
                    Me.TurninDateField = value
                    Me.RaisePropertyChanged("TurninDate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Page", [Namespace]:="http://schemas.datacontract.org/2004/07/AdUpdates"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Page
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActiveIndicatorField As AdUpdates.ActiveIndicatorType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CoverPageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShotGroupField() As AdUpdates.ShotGroup
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActiveIndicator() As AdUpdates.ActiveIndicatorType
            Get
                Return Me.ActiveIndicatorField
            End Get
            Set
                If (Me.ActiveIndicatorField.Equals(value) <> true) Then
                    Me.ActiveIndicatorField = value
                    Me.RaisePropertyChanged("ActiveIndicator")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdNumber() As String
            Get
                Return Me.AdNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdNumberField, value) <> true) Then
                    Me.AdNumberField = value
                    Me.RaisePropertyChanged("AdNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CoverPage() As String
            Get
                Return Me.CoverPageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CoverPageField, value) <> true) Then
                    Me.CoverPageField = value
                    Me.RaisePropertyChanged("CoverPage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageDescription() As String
            Get
                Return Me.PageDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PageDescriptionField, value) <> true) Then
                    Me.PageDescriptionField = value
                    Me.RaisePropertyChanged("PageDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageNumber() As Integer
            Get
                Return Me.PageNumberField
            End Get
            Set
                If (Me.PageNumberField.Equals(value) <> true) Then
                    Me.PageNumberField = value
                    Me.RaisePropertyChanged("PageNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShotGroup() As AdUpdates.ShotGroup()
            Get
                Return Me.ShotGroupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ShotGroupField, value) <> true) Then
                    Me.ShotGroupField = value
                    Me.RaisePropertyChanged("ShotGroup")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ActiveIndicatorType", [Namespace]:="http://schemas.datacontract.org/2004/07/AdUpdates")>  _
    Public Enum ActiveIndicatorType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        A = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        K = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ShotGroup", [Namespace]:="http://schemas.datacontract.org/2004/07/AdUpdates"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ShotGroup
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImagesField() As AdUpdates.Image
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShotNumberField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Images() As AdUpdates.Image()
            Get
                Return Me.ImagesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImagesField, value) <> true) Then
                    Me.ImagesField = value
                    Me.RaisePropertyChanged("Images")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShotNumber() As Integer
            Get
                Return Me.ShotNumberField
            End Get
            Set
                If (Me.ShotNumberField.Equals(value) <> true) Then
                    Me.ShotNumberField = value
                    Me.RaisePropertyChanged("ShotNumber")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Image", [Namespace]:="http://schemas.datacontract.org/2004/07/AdUpdates"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Image
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActiveIndicatorField As AdUpdates.ActiveIndicatorType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageClassField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageNotesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageNumberField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageSourceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageSuffixTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MediaTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SamplesField() As AdUpdates.MerchForImage
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActiveIndicator() As AdUpdates.ActiveIndicatorType
            Get
                Return Me.ActiveIndicatorField
            End Get
            Set
                If (Me.ActiveIndicatorField.Equals(value) <> true) Then
                    Me.ActiveIndicatorField = value
                    Me.RaisePropertyChanged("ActiveIndicator")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageClass() As String
            Get
                Return Me.ImageClassField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageClassField, value) <> true) Then
                    Me.ImageClassField = value
                    Me.RaisePropertyChanged("ImageClass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageNotes() As String
            Get
                Return Me.ImageNotesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageNotesField, value) <> true) Then
                    Me.ImageNotesField = value
                    Me.RaisePropertyChanged("ImageNotes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageNumber() As Integer
            Get
                Return Me.ImageNumberField
            End Get
            Set
                If (Me.ImageNumberField.Equals(value) <> true) Then
                    Me.ImageNumberField = value
                    Me.RaisePropertyChanged("ImageNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageSource() As String
            Get
                Return Me.ImageSourceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageSourceField, value) <> true) Then
                    Me.ImageSourceField = value
                    Me.RaisePropertyChanged("ImageSource")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageSuffixType() As String
            Get
                Return Me.ImageSuffixTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageSuffixTypeField, value) <> true) Then
                    Me.ImageSuffixTypeField = value
                    Me.RaisePropertyChanged("ImageSuffixType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MediaType() As String
            Get
                Return Me.MediaTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MediaTypeField, value) <> true) Then
                    Me.MediaTypeField = value
                    Me.RaisePropertyChanged("MediaType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Samples() As AdUpdates.MerchForImage()
            Get
                Return Me.SamplesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SamplesField, value) <> true) Then
                    Me.SamplesField = value
                    Me.RaisePropertyChanged("Samples")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MerchForImage", [Namespace]:="http://schemas.datacontract.org/2004/07/AdUpdates"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MerchForImage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActiveIndicatorField As AdUpdates.ActiveIndicatorType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MerchIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StylingNotesField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ActiveIndicator() As AdUpdates.ActiveIndicatorType
            Get
                Return Me.ActiveIndicatorField
            End Get
            Set
                If (Me.ActiveIndicatorField.Equals(value) <> true) Then
                    Me.ActiveIndicatorField = value
                    Me.RaisePropertyChanged("ActiveIndicator")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MerchID() As String
            Get
                Return Me.MerchIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MerchIDField, value) <> true) Then
                    Me.MerchIDField = value
                    Me.RaisePropertyChanged("MerchID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StylingNotes() As String
            Get
                Return Me.StylingNotesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StylingNotesField, value) <> true) Then
                    Me.StylingNotesField = value
                    Me.RaisePropertyChanged("StylingNotes")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AdUpdates.IAd")>  _
    Public Interface IAd
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAd/GetAdChangeInfo", ReplyAction:="http://tempuri.org/IAd/GetAdChangeInfoResponse")>  _
        Function GetAdChangeInfo(ByVal Id As Integer) As AdUpdates.Ad()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAd/GetAdChangeInfo", ReplyAction:="http://tempuri.org/IAd/GetAdChangeInfoResponse")>  _
        Function GetAdChangeInfoAsync(ByVal Id As Integer) As System.Threading.Tasks.Task(Of AdUpdates.Ad())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAdChannel
        Inherits AdUpdates.IAd, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AdClient
        Inherits System.ServiceModel.ClientBase(Of AdUpdates.IAd)
        Implements AdUpdates.IAd
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAdChangeInfo(ByVal Id As Integer) As AdUpdates.Ad() Implements AdUpdates.IAd.GetAdChangeInfo
            Return MyBase.Channel.GetAdChangeInfo(Id)
        End Function
        
        Public Function GetAdChangeInfoAsync(ByVal Id As Integer) As System.Threading.Tasks.Task(Of AdUpdates.Ad()) Implements AdUpdates.IAd.GetAdChangeInfoAsync
            Return MyBase.Channel.GetAdChangeInfoAsync(Id)
        End Function
    End Class
End Namespace
