'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PrintPreTurnInCtrl

    '''<summary>
    '''RadAjaxManagerProxy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerProxy1 As Global.Telerik.Web.UI.RadAjaxManagerProxy

    '''<summary>
    '''tblPrintPreTurnInAdLevelCtrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPrintPreTurnInAdLevelCtrl As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblAdNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbAdNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAdNo As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblPageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbPageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPageNo As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblFOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbFOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFOB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tblPrintPreTurnInCtrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPrintPreTurnInCtrl As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDept As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDept As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbClass As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblACode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbACode As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblCreatedSince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedSince As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dpCreatedSince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpCreatedSince As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorStyle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbVendorStyle As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddVendorStyle As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''listBoxVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listBoxVendorStyle As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''imgRemoveVendorStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRemoveVendorStyle As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblOR1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOR1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbISN As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddISN As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''listBoxISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listBoxISN As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''imgRemoveISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRemoveISN As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblOR2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOR2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReserveISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReserveISN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbReserverISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbReserverISN As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''imgAddReserveISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddReserveISN As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''listBoxReserveISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listBoxReserveISN As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''imgRemoveReserveISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRemoveReserveISN As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblOR3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOR3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAddTBDItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddTBDItem As Global.System.Web.UI.WebControls.Button
End Class
