'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PrintTurnInMaintctrl

    '''<summary>
    '''rAPMPrintTurnInMaintctrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rAPMPrintTurnInMaintctrl As Global.Telerik.Web.UI.RadAjaxManagerProxy

    '''<summary>
    '''tblPrintTurnInMaintctrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPrintTurnInMaintctrl As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblAdNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbAdNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAdNo As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblPageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbPageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPageNo As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblCRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCRG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbCRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCRG As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblCMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCMG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbCMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCMG As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblFOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbFOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFOB As Global.Telerik.Web.UI.RadComboBox
End Class
