//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogEstimating.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatalogEstimating.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PROD).
        /// </summary>
        internal static string ApplicationEnvironment {
            get {
                return ResourceManager.GetString("ApplicationEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you wish to exit?.
        /// </summary>
        internal static string ApplicationExitDirtyWarning {
            get {
                return ResourceManager.GetString("ApplicationExitDirtyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly and Distribution must be set prior to Distribution Mapping..
        /// </summary>
        internal static string AssemblyDistributionRequired {
            get {
                return ResourceManager.GetString("AssemblyDistributionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon BonTonDiamond {
            get {
                object obj = ResourceManager.GetObject("BonTonDiamond", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes.  Are you sure you wish to Cancel and lose your changes?.
        /// </summary>
        internal static string CancelChangesWarning {
            get {
                return ResourceManager.GetString("CancelChangesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must save this estimate before it can be added to a polybag group..
        /// </summary>
        internal static string CannotAddUnsavedEstimateToPolybagError {
            get {
                return ResourceManager.GetString("CannotAddUnsavedEstimateToPolybagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made changes..
        /// </summary>
        internal static string ChangesMade {
            get {
                return ResourceManager.GetString("ChangesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one component must be entered to enable mapping..
        /// </summary>
        internal static string ComponentRequiredToMap {
            get {
                return ResourceManager.GetString("ComponentRequiredToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No components found which match your search criteria..
        /// </summary>
        internal static string ComponentSearchNoRecords {
            get {
                return ResourceManager.GetString("ComponentSearchNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CopyDialog {
            get {
                object obj = ResourceManager.GetObject("CopyDialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default rate must be selected..
        /// </summary>
        internal static string DefaultItemRequired {
            get {
                return ResourceManager.GetString("DefaultItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to permanently delete this polybag group.  Are you sure?.
        /// </summary>
        internal static string DeletePolybagGroupWarning {
            get {
                return ResourceManager.GetString("DeletePolybagGroupWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to permanently delete these rates.  Are you sure?.
        /// </summary>
        internal static string DeleteRateSetWarning {
            get {
                return ResourceManager.GetString("DeleteRateSetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this rate?.
        /// </summary>
        internal static string DeleteRateWarning {
            get {
                return ResourceManager.GetString("DeleteRateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to permanently delete this scenario.  Are you sure?.
        /// </summary>
        internal static string DeleteScenarioWarning {
            get {
                return ResourceManager.GetString("DeleteScenarioWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each Category can have only one row selected as Active..
        /// </summary>
        internal static string DuplicateActiveError {
            get {
                return ResourceManager.GetString("DuplicateActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions must be unique.
        /// </summary>
        internal static string DuplicateDescriptionError {
            get {
                return ResourceManager.GetString("DuplicateDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display order values must be unique.
        /// </summary>
        internal static string DuplicateDisplayOrderError {
            get {
                return ResourceManager.GetString("DuplicateDisplayOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate effective dates are not allowed..
        /// </summary>
        internal static string DuplicateEffectiveDateError {
            get {
                return ResourceManager.GetString("DuplicateEffectiveDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate items are not allowed..
        /// </summary>
        internal static string DuplicateItemError {
            get {
                return ResourceManager.GetString("DuplicateItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combination of Description, Weight and Grade must be unique..
        /// </summary>
        internal static string DuplicatePaperMapError {
            get {
                return ResourceManager.GetString("DuplicatePaperMapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID&apos;s must be unique..
        /// </summary>
        internal static string DuplicateVendorID {
            get {
                return ResourceManager.GetString("DuplicateVendorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was returned for this report..
        /// </summary>
        internal static string EmptyReportWarning {
            get {
                return ResourceManager.GetString("EmptyReportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        internal static string EstimateFormTitle {
            get {
                return ResourceManager.GetString("EstimateFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No estimates found which match your search criteria..
        /// </summary>
        internal static string EstimateSearchNoRecords {
            get {
                return ResourceManager.GetString("EstimateSearchNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have a rate for both CWT and Flat.  One or both must be zero..
        /// </summary>
        internal static string FreightRateConflict {
            get {
                return ResourceManager.GetString("FreightRateConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes you made to the insert scenario are invalid..
        /// </summary>
        internal static string InsertScenarioChangesLine1 {
            get {
                return ResourceManager.GetString("InsertScenarioChangesLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue, all changes to the insert scenario will be lost..
        /// </summary>
        internal static string InsertScenarioChangesLine2 {
            get {
                return ResourceManager.GetString("InsertScenarioChangesLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is invalid data..
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is invalid data. Are you sure you wish to leave this tab?.
        /// </summary>
        internal static string InvalidDataWarning {
            get {
                return ResourceManager.GetString("InvalidDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentages must be between 0.00 and 100.00.
        /// </summary>
        internal static string InvalidPercentageError {
            get {
                return ResourceManager.GetString("InvalidPercentageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kill {
            get {
                object obj = ResourceManager.GetObject("Kill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Do you wish to lose changes before switching tabs?.
        /// </summary>
        internal static string LeaveTabCancelWarning {
            get {
                return ResourceManager.GetString("LeaveTabCancelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoMedium {
            get {
                object obj = ResourceManager.GetObject("LogoMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoSmall {
            get {
                object obj = ResourceManager.GetObject("LogoSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue, all unsaved changes will be lost.  Are you sure?.
        /// </summary>
        internal static string LoseUnsavedChanges {
            get {
                return ResourceManager.GetString("LoseUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer Print Media Estimating System.
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one row may be selected as default..
        /// </summary>
        internal static string MultipleDefaultsError {
            get {
                return ResourceManager.GetString("MultipleDefaultsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewEstimate {
            get {
                object obj = ResourceManager.GetObject("NewEstimate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewPolybag {
            get {
                object obj = ResourceManager.GetObject("NewPolybag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string NewRecordWarningCaption {
            get {
                return ResourceManager.GetString("NewRecordWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current record contains invalid data..
        /// </summary>
        internal static string NewRecordWarningLine1 {
            get {
                return ResourceManager.GetString("NewRecordWarningLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue, any unsaved changes will be lost..
        /// </summary>
        internal static string NewRecordWarningLine2 {
            get {
                return ResourceManager.GetString("NewRecordWarningLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must open a polybag group prior to attempting this operation..
        /// </summary>
        internal static string NoOpenPolybagGroupsError {
            get {
                return ResourceManager.GetString("NoOpenPolybagGroupsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save a Polybag Group without at least 2 estimates in it..
        /// </summary>
        internal static string NotEnoughEstimatesError {
            get {
                return ResourceManager.GetString("NotEnoughEstimatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenReadOnly {
            get {
                object obj = ResourceManager.GetObject("OpenReadOnly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group cannot be added.  It is already included in this estimate..
        /// </summary>
        internal static string OverlapGroup {
            get {
                return ResourceManager.GetString("OverlapGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group cannot be added because the following publication/location(s) are already included in this estimate:.
        /// </summary>
        internal static string OverlapGroupPubLoc {
            get {
                return ResourceManager.GetString("OverlapGroupPubLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This scenario cannot be added.  It is already included in this estimate..
        /// </summary>
        internal static string OverlapScenario {
            get {
                return ResourceManager.GetString("OverlapScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This scenario cannot be added because the following group(s) are already included in this estimate:.
        /// </summary>
        internal static string OverlapScenarioGroup {
            get {
                return ResourceManager.GetString("OverlapScenarioGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This scenario cannot be added because the following publication/location(s) are included multiple times in this scenario for this run date:.
        /// </summary>
        internal static string OverlapScenarioInternalPubLoc {
            get {
                return ResourceManager.GetString("OverlapScenarioInternalPubLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This scenario cannot be added because the following publication/location(s) are already included in this estimate:.
        /// </summary>
        internal static string OverlapScenarioPubLoc {
            get {
                return ResourceManager.GetString("OverlapScenarioPubLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This publication/location cannot be added.  It is already included in this estimate..
        /// </summary>
        internal static string OverlapSinglePubLoc {
            get {
                return ResourceManager.GetString("OverlapSinglePubLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All percentages must add up to 100.
        /// </summary>
        internal static string PercentNot100Error {
            get {
                return ResourceManager.GetString("PercentNot100Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polybag.
        /// </summary>
        internal static string PolybagFormTitle {
            get {
                return ResourceManager.GetString("PolybagFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each polybag must have at least two packages.
        /// </summary>
        internal static string PolybagRequiresMinPackages {
            get {
                return ResourceManager.GetString("PolybagRequiresMinPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No polybags found which match your search criteria..
        /// </summary>
        internal static string PolybagSearchNoRecords {
            get {
                return ResourceManager.GetString("PolybagSearchNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combination of Postage Class, Mailer Type, and Effective Date has resulted in no available categories for this scenario..
        /// </summary>
        internal static string PostalCategoryListEmpty {
            get {
                return ResourceManager.GetString("PostalCategoryListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this row, it is in use by one or more Postal Rates..
        /// </summary>
        internal static string PostalRateDeleteError {
            get {
                return ResourceManager.GetString("PostalRateDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete Postal Rate.  It is being referenced by one or more postal scenarios..
        /// </summary>
        internal static string PostalRateRefDeleteWarning {
            get {
                return ResourceManager.GetString("PostalRateRefDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify Postal Rate.  It is being referenced by one or more postal scenarios..
        /// </summary>
        internal static string PostalRateRefModifyWarning {
            get {
                return ResourceManager.GetString("PostalRateRefModifyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new postal scenario you have entered is incomplete and cannot be saved..
        /// </summary>
        internal static string PostalScenarioIncomplete {
            get {
                return ResourceManager.GetString("PostalScenarioIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to purge these records?  This action cannot be undone..
        /// </summary>
        internal static string PurgeWarning {
            get {
                return ResourceManager.GetString("PurgeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must either create or search for a publication location activation date..
        /// </summary>
        internal static string RequirePubRateMapActivate {
            get {
                return ResourceManager.GetString("RequirePubRateMapActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAll {
            get {
                object obj = ResourceManager.GetObject("SaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the publication and location that you would like to create publication information for..
        /// </summary>
        internal static string SelectPubLocation {
            get {
                return ResourceManager.GetString("SelectPubLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Publication.
        /// </summary>
        internal static string SelectPubLocationCaption {
            get {
                return ResourceManager.GetString("SelectPubLocationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sync {
            get {
                object obj = ResourceManager.GetObject("Sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Breakdown Description is required and must be unique..
        /// </summary>
        internal static string UniqueDistBreakdownDesc {
            get {
                return ResourceManager.GetString("UniqueDistBreakdownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unkill {
            get {
                object obj = ResourceManager.GetObject("Unkill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Upload {
            get {
                object obj = ResourceManager.GetObject("Upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Validate {
            get {
                object obj = ResourceManager.GetObject("Validate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vendor rate doesn&apos;t exist for the given effective date..
        /// </summary>
        internal static string VendorRateDoesntExist {
            get {
                return ResourceManager.GetString("VendorRateDoesntExist", resourceCulture);
            }
        }
    }
}
