'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GXSCopyView

    '''<summary>
    '''GXSCopyViewCtrl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GXSCopyViewCtrl1 As Global.TurnInProcessAutomation.GXSCopyViewCtrl

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As TurnInProcessAutomation.ContentPage
        Get
            Return CType(MyBase.Master, TurnInProcessAutomation.ContentPage)
        End Get
    End Property
End Class
